# Generated by Django 6.0.3 on 2026-04-14 23:54

from django.db import migrations, models


def normalize_existing_user_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.exclude(role__in=["administrator", "general_user"]).update(
        role="general_user"
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("general_user", "General User"),
                ],
                default="general_user",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_existing_user_roles, noop_reverse),
    ]
