# Generated by Django 6.0.3 on 2026-04-15 00:02

from django.db import migrations, models


def normalize_roles_to_administrator(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.exclude(role="administrator").update(role="administrator")


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_name_user_position_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(normalize_roles_to_administrator, noop_reverse),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("administrator", "Administrator")],
                default="administrator",
                max_length=20,
            ),
        ),
    ]
