# Generated by Django 6.0.3 on 2026-04-22 11:59

from django.db import migrations, models


def migrate_position_to_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    position_role_map = {
        "formator": "formator",
        "need formator": "formator",
        "staff": "staff",
    }
    for user in User.objects.all():
        position = (user.position or "").strip().lower()
        mapped = position_role_map.get(position)
        if mapped:
            user.role = mapped
            User.objects.filter(pk=user.pk).update(role=mapped)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("formator", "Formator"),
                    ("staff", "Staff"),
                ],
                default="administrator",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_position_to_role, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
    ]
