# Generated by Django 6.0.3 on 2026-04-23 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "contact_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please input a valid mobile number (09XXXXXXXXX)",
                                regex="^09\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Needs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("objectives", models.TextField(blank=True)),
                ("expected_outcomes", models.TextField(blank=True)),
                ("skills_needed", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("vision", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("core_values", models.TextField(blank=True)),
                ("date_established", models.DateField()),
                ("sec_registration", models.CharField(max_length=255)),
                ("bir_registration", models.CharField(max_length=255)),
                ("tin", models.CharField(max_length=255)),
                ("moa_start_date", models.DateField(blank=True, null=True)),
                ("moa_end_date", models.DateField(blank=True, null=True)),
                ("moa_link", models.URLField(blank=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PastInterventions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("outcomes", models.TextField(blank=True)),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField(blank=True, null=True)),
                ("output_link", models.URLField(blank=True)),
                ("pictures_link", models.URLField(blank=True)),
                ("evaluation_link", models.URLField(blank=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SocioEconomicProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("population_size", models.IntegerField()),
                ("population_breakdown", models.TextField(blank=True)),
                ("livelihoods", models.TextField(blank=True)),
                ("health_profile", models.TextField(blank=True)),
                ("sociocultural_profile", models.TextField(blank=True)),
                ("political_profile", models.TextField(blank=True)),
                ("partner_networks", models.TextField(blank=True)),
                ("resources_available", models.TextField(blank=True)),
                ("vulnerabilities", models.TextField(blank=True)),
                ("housing", models.TextField(blank=True)),
                ("transportation", models.TextField(blank=True)),
                ("electricity", models.TextField(blank=True)),
                ("water", models.TextField(blank=True)),
                ("wet_market", models.TextField(blank=True)),
                ("health_facilities", models.TextField(blank=True)),
                ("education_facility", models.TextField(blank=True)),
                ("telecommunication", models.TextField(blank=True)),
                ("others", models.TextField(blank=True)),
            ],
        ),
    ]
