# Generated by Django 6.0.3 on 2026-03-22 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_issued", models.DateField()),
                ("termination_date", models.DateField()),
                ("with_amendment", models.BooleanField(default=False)),
                ("programs_included", models.TextField(blank=True)),
                ("scanned_moa", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "MOA",
                "verbose_name_plural": "MOAs",
                "ordering": ["-date_issued"],
                "get_latest_by": "date_issued",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(blank=True, max_length=20)),
                ("area_code", models.CharField(max_length=20, unique=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Urban Poor", "Urban Poor"),
                            ("Rural Poor", "Rural Poor"),
                            ("Environment", "Environment"),
                            ("Education", "Education"),
                            ("Health", "Health"),
                            ("Disaster", "Disaster"),
                            ("Indigenous Peoples", "Indigenous Peoples"),
                            ("Workers", "Workers"),
                            ("Women", "Women"),
                            ("Youth", "Youth"),
                            ("Persons with Disabilities", "Persons with Disabilities"),
                            ("Elderly", "Elderly"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(max_length=255)),
                ("google_maps_link", models.URLField(blank=True, max_length=500)),
                (
                    "ncr_or_province",
                    models.CharField(
                        blank=True,
                        choices=[("NCR+", "NCR+"), ("Province", "Province")],
                        max_length=10,
                    ),
                ),
                ("point_person", models.CharField(max_length=100)),
                ("head_of_office", models.CharField(max_length=100)),
                (
                    "contact_no",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please input a valid mobile number (09XXXXXXXXX)",
                                regex="^09\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("On Hold", "On Hold"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
    ]
