# Generated by Django 6.0.3 on 2026-04-07 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pastinterventions',
            name='formator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programs',
            name='community_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='socioeconomicprofile',
            name='community_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socioeconomic_profiles', to='partners.partner'),
        ),
    ]
