# Generated by Django 6.0.3 on 2026-04-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_partners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="needs",
            name="community_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="needs",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="community_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="pastinterventions",
            name="community_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="past_interventions",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="pastinterventions",
            name="formator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socioeconomicprofile",
            name="community_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socioeconomic_profiles",
                to="partners.partner",
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["name"], name="partners_pa_name_057e86_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="partners_pa_updated_669fbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["date_established"], name="partners_pa_date_es_b549c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["moa_start_date"], name="partners_pa_moa_sta_af03ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["moa_end_date"], name="partners_pa_moa_end_e1fd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_by"], name="partners_pa_updated_30ecc3_idx"
            ),
        ),
    ]
