# Generated by Django 6.0.3 on 2026-04-14 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partner_moa_and_audit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["name"], name="partners_pa_name_057e86_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="partners_pa_updated_669fbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["date_established"], name="partners_pa_date_es_b549c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["moa_start_date"], name="partners_pa_moa_sta_af03ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["moa_end_date"], name="partners_pa_moa_end_e1fd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_by"], name="partners_pa_updated_30ecc3_idx"
            ),
        ),
    ]
