# Generated by Django 6.0.3 on 2026-04-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partner_partners_pa_name_057e86_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="designation",
        ),
    ]
