# Generated by Django 6.0.3 on 2026-04-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_remove_contact_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="pastinterventions",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RenameModel(
            old_name="Programs",
            new_name="Needs",
        ),
        migrations.AlterModelTable(
            name="needs",
            table="Needs",
        ),
        migrations.AlterField(
            model_name="needs",
            name="community_partner",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="needs",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="needs",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
