# Generated by Django 6.0.3 on 2026-04-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_partner_is_archived_pastinterventions_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="needs",
            table=None,
        ),
    ]
