# Generated by Django 6.0.3 on 2026-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Binhi", "Binhi"),
                            ("Punla", "Punla"),
                            ("Bigkis", "Bigkis"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2-day Live Out", "2-day Live Out"),
                            ("3-day Live Out", "3-day Live Out"),
                            ("Stay In", "Stay In"),
                        ],
                        max_length=15,
                    ),
                ),
                ("week", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Go", "Go"),
                            ("Accomplished", "Accomplished"),
                            ("Postponed", "Postponed"),
                            ("Dissolved", "Dissolved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("num_slots", models.PositiveIntegerField(default=0)),
                ("num_groups", models.PositiveIntegerField(default=0)),
                ("max_members_per_group", models.PositiveIntegerField(default=0)),
                ("num_deputies_needed", models.PositiveIntegerField(default=0)),
                ("special_remarks", models.TextField(blank=True)),
                ("course_orientation", models.DateTimeField(blank=True, null=True)),
                ("binhi_orientation", models.DateTimeField(blank=True, null=True)),
                (
                    "binhi_orientation_venue",
                    models.CharField(blank=True, max_length=255),
                ),
                ("integration_session", models.DateTimeField(blank=True, null=True)),
                (
                    "integration_session_venue",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "area_engagement_assembly",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_session", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_session_venue",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "integration_presentation",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EngagementTransportation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_of_transportation",
                    models.CharField(blank=True, max_length=100),
                ),
                ("duration_days", models.PositiveIntegerField(default=0)),
                ("total_passengers", models.PositiveIntegerField(default=0)),
                ("num_vehicles_needed", models.PositiveIntegerField(default=0)),
                (
                    "cash_advance_commute",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "km_two_way",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("driver_assembly_time", models.TimeField(blank=True, null=True)),
                ("admu_arrival_time", models.TimeField(blank=True, null=True)),
                ("meetup_place", models.CharField(blank=True, max_length=255)),
                (
                    "excess_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "km_formula_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "subtotal_km_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "excess_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "time_formula_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_cost_with_permits",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                ("course", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=50)),
                ("classroom", models.CharField(blank=True, max_length=100)),
                ("faculty", models.CharField(max_length=255)),
                ("schedule", models.CharField(blank=True, max_length=255)),
                ("num_students", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
