# Generated by Django 6.0.3 on 2026-03-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0002_initial"),
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="areaengagement",
            name="deputies",
            field=models.ManyToManyField(
                blank=True,
                related_name="area_engagements_as_deputy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="areaengagement",
            name="formator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="area_engagements_as_formator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="areaengagement",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_engagements",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="engagementtransportation",
            name="area_engagement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportation",
                to="programs.areaengagement",
            ),
        ),
        migrations.AddField(
            model_name="areaengagement",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_engagements",
                to="programs.section",
            ),
        ),
    ]
